### ISSUE TITLE
`value` not used in self attention

### ISSUE THREAD

**Issue by lxuechen** [hmdolatabadi/denoising_diffusion#1]
Hi, thanks for porting the official tf code to pytorch.

I read [this](https://github.com/hmdolatabadi/denoising_diffusion/blob/392d59a95a85b0ac19918c9b3174d1a71be1c5d1/lib/model.py#L143) self attention code and found that `value` is not used. I think this will likely affect performance, though perhaps quite subtly, and likely undetected w/o evaluating log-likelihoods and FID.

**Comment by hmdolatabadi** [comment]
Dear Xuechen,

Thanks for reporting this issue. You're absolutely right, and I'll correct and test it soon.
Yeah, model selection using FID, as in the original paper, is very costly and cannot be done with my limited computational resources.

Thanks again,
Hadi.
